server.port: 9801

eventexcutor: 
  core-pool-size: 50
  max-pool-size: 100
  queue-capacity: 5000
  keep-alive-seconds: 300
  thread-name-prefix: EVENT_DEFAULT_EXCUTOR

autzone: 
  helloTask: 
    enable: false
    eventexcutor: 
      core-pool-size: 1
      max-pool-size: 1
      queue-capacity: 10
      keep-alive-seconds: 10
      thread-name-prefix: HELLO_WORLD

spring:
  application: 
    name: 智慧助手
  datasource:
    jdbc-url: jdbc:mysql:/localhost:3306/smart_event?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
#Swagger Configure Properties
sop:
  swagger:
    enable: true
    packageScan: site.autzone.event.handler.rest
    title: Restfull API
    description: Restfull API
    version: 1.0
